//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacion_Articulos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo_Facturable
    {
        public int ID_Articulo { get; set; }
        public string Nombre_Articulo { get; set; }
        public double Costo_Unitario { get; set; }
        public double Precio_Unitario { get; set; }
        public int Cantidad { get; set; }
        public string Estado { get; set; }
    }
}
