//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacion_Articulos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Condicion_Pago
    {
        public int ID_Condicion { get; set; }
        public string Descripcion { get; set; }
        public int Cantidad_dias { get; set; }
        public string Estado { get; set; }
    }
}
