//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacion_Articulos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.Articulo_Facturable = new HashSet<Articulo_Facturable>();
        }
    
        public int ID_Factura { get; set; }
        public string Forma_Pago { get; set; }
        public int ID_Vendedor { get; set; }
        public int ID_Cliente { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Comentario { get; set; }
        public int ID_Articulo { get; set; }
        public int Cantidad { get; set; }
        public double Precio_Unitario { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Vendedor Vendedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Articulo_Facturable> Articulo_Facturable { get; set; }
    }
}
